export const DepartmentMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Department",
      field: "name",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Description",
      field: "description",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const CountryMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Country",
      field: "name",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Code",
      field: "code",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const LevelMasterColumnDefs = [
    {
      headerName: "Sl No.",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Unique ID",
      field: "unique_id",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Level",
      field: "level",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const LeaveTypeMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Leave Type",
      field: "name",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Description",
      field: "description",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];