import { filterParams } from "../UI/Utils/DateFilter";

export const DepartmentMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Department",
      field: "name",
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Description",
      field: "description",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const CountryMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Country",
      field: "name",
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Code",
      field: "code",
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Paternity Leave Applicable",
      field: "paternityLeaveApplicable",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const LevelMasterColumnDefs = [
    {
      headerName: "Sl No.",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Unique ID",
      field: "unique_id",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Level",
      field: "level",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const LeaveTypeMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Leave Type",
      field: "name",
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Description",
      field: "description",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const PublicHolidaysMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Country",
      field: "countryName",
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Name",
      field: "name",
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Description",
      field: "description",
      sortable: true,
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Date",
      field: "date",
      filter: 'agDateColumnFilter',
      filterParams: filterParams,
      sortable: true,
      editable: false,
      resizable: true,
      width: 100,
      cellRenderer: "dateRenderer",
    },
    {
      headerName: "Year",
      field: "year",
      filter: 'agNumberColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      width: 100,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const LeaveEntitlementMasterColumnDefs = [
    {
      headerName: "Id",
      field: "id",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Country",
      field: "contryName",
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Leave Type",
      field: "leaveTypeName",
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Leave Count",
      field: "leaveCount",
      sortable: true,
      filter: 'agNumberColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      editable: false,
      resizable: true,
      // width: 100,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];
  export const EmployeeManagementColumnDefs = [
    {
      headerName: "Emp. ID",
      field: "employeeId",
      sortable: true,
      editable: false,
      resizable: true,
      width: 70,
    },
    {
      headerName: "Employee Name",
      field: "firstName",
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      sortable: true,
      editable: false,
      resizable: true,
      // width: 350,
    },
    {
      headerName: "Designation",
      field: "designation",
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      editable: false,
      resizable: true,
    },
    {
      headerName: "Department",
      field: "department",
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      editable: false,
      resizable: true,
    },
    {
      headerName: "Approver",
      field: "reportsToName",
      sortable: true,
      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset'],
      },
      editable: false,
      resizable: true,
    },
    {
      headerName: "Actions",
      field: "actions",
      sortable: false,
      editable: false,
      resizable: false,
      width: 70,
      cellRenderer: "statusRenderer",
    },
  ];